services:
  - type: web
    name: adimma-kann-bot
    env: python
    region: oregon
    plan: free
    branch: main
    runtime: python
    buildCommand: |
      python --version
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: GROQ_API_KEY1
        sync: false
      - key: GROQ_API_KEY2
        sync: false
      - key: GROQ_API_KEY3
        sync: false
      - key: WEBHOOK_URL
        sync: false
      - key: OWNER_ID
        value: 733340342
      - key: PORT
        value: 10000
      - key: PYTHON_VERSION
        value: 3.11.0
    disk:
      name: tts-cache
      mountPath: /opt/render/project/src/tts_cache
      sizeGB: 1
