services:
  - type: web
    name: adimma-kann
    runtime: python
    repo: https://github.com/asnzodiac/Adimma-Kann.git
    branch: main
    rootDir: .
    plan: free
    region: oregon
    buildCommand: |
      apt-get update && apt-get install -y ffmpeg
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: gunicorn bot:app --bind 0.0.0.0:$PORT --workers 1 --threads 4 --timeout 120
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: GROQ_API_KEY1
        sync: false
      - key: GROQ_API_KEY2
        sync: false
      - key: GROQ_API_KEY3
        sync: false
      - key: PORT
        value: 5000
    autoDeploy: true
